void os(void)
{
	const char *str = "ALOKEDIP CHOUDHURI , THIS IS A MESSEGE FROM A KERNEL WRITTEN IN C";
	char *c = (char*)0xb8000;	//c IS THE CHARECTER POINTER POINT TO THE STARTING MEMORY CHUNK OF VIDEOMEMORY WHICH IS 0XB8000
	int i = 0;
	int j = 0;
	while(j < 80 * 25 * 2) {	// THIS I/O SCREENS ONLY HAS 25 ROWS AND EACH ROW HAS 80 ASCII CHARECTERS OF(8+8) 16 BYTES
		c[j] = ' ';		// FIRST 8 BYTES STANDS FOR THE ASCII CHARECTER
		c[j+1] = 0x02; 		//NEXT 8 BYTES ARE FOR COLOR. 0X02 STAND FOR GREEN COLOR CURSOR WILL BE GREEN
		j = j + 2;	
	}
	j = 0;
	while(str[j] != '\0') {
		c[i] = str[j];
		c[i+1] = 0x01;		//0X01 STANDS FOR BLUE CHARECTER WILL BE BLUE
		j++;
		i = i + 2;
	}
	return;
}
